examples/sign/README.md, examples/sign/sign_trainer.py, examples/sign/sign_utils.py, gammagl/datasets/flickr.py, gammagl/models/sign.py
模型、trianer、readme、以及flickr数据集的处理。
torch、tf都跑了
=> [MODEL] sign

examples/grace/eval.py, examples/grace/grace_trainer.py, examples/grace/readme.md, gammagl/models/grace.py, gammagl/utils/corrupt_graph.py
grace模型，只能支持tensorflow，因为，update操作的问题，无tlx。update的操作，我无法处理多框架后端
打乱图的utils，以及测试的readme。修改结果、之前老版本的结果当前的超参对不上，只能后续继续测试，
=> [Model] Grace

examples/graphsage/reddit_sage.py, gammagl/datasets/reddit.py, gammagl/layers/conv/sage_conv.py, gammagl/models/graphsage.py
=> [MODEL] sage修改

.github/PULL_REQUEST_TEMPLATE.md
=> [Template] Create pr template

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/questions-help-support.md, .readthedocs.yaml
Create issue template.
Add issue template. Create .readthedocs.yaml.
=> [Template] Create issue template

gammagl/datasets/reddit.py, gammagl/loader/Neighbour_sampler.py
跟鹏程交流的意思是，他们的loader的init中，最好出现的还是numpy，并且，我也试了一下，确实np速度更好，并且增加了当没有rowptr的操作。但仍然默认edge是有序的。num_work在全部使用tensor后，可以使用了
reddit数据集稍微处理一下，删除中文
=> [SAMPLE] fix

examples/agnn/agnn_trainer.py, examples/agnn/readme.md, gammagl/layers/conv/agnn_conv.py
@clearhanhui 
Existing issue: The model run slowly when using torch or paddle benkend
=> Model(agnn)

examples/graphsage/reddit_sage.py, gammagl/datasets/reddit.py
=> [MODEL] graphsage

gammagl/datasets/amazon.py, gammagl/datasets/coauthor.py, gammagl/io/npz.py, gammagl/utils/coalesce.py, gammagl/utils/loop.py, gammagl/utils/undirected.py
add coalesce.py
update loop.py
add undirected.py
=> add coalesce.py update loop.py add undirected.py

examples/InfoGraph/infograph_eval.py, examples/InfoGraph/infograph_trainer.py, examples/InfoGraph/infograph_util.py, examples/InfoGraph/readme.md, gammagl/layers/conv/__init__.py, gammagl/layers/conv/gin_conv.py, gammagl/models/infograph.py
这里实现了infograph的代码，可以在TensorFlow后端进行运行，pytorch和paddle后端目前和斯源学长可能是tensorlayerx的问题，暂时不能运行，所以我的readme也只测试了tf的准确率
=> infograph功能完成

README.md, docs/source/notes/installation.rst, docs/source/notes/introduction.rst, gammagl/utils/loop.py
Create installation documents and fix some bugs.
installation.rst: create document.
README.md, introduction.rst, gammagl.utils.loop.py: fix some bugs
=> [Docs] Create docs and fix docs bugs

README.md
=> [Update]README.md update

examples/merit/REMADE.md, examples/merit/eval.py, examples/merit/merit_trainer.py, examples/merit/process.py, gammagl/models/merit.py
=> [Model] merit

examples/simplehgn/simplehgn_trainer.py, gammagl/layers/conv/__init__.py, gammagl/layers/conv/simplehgn_conv.py, tests/layers/conv/test_simplehgn_conv.py
=> [Model]fix model bugs

gammagl/mpops/torch_segment/CMakeLists.txt, gammagl/mpops/torch_segment/readme.md, gammagl/mpops/torch_segment/segment_max.cpp, profiler/mpops/torch_ext.py
=> segment_max cpu version

gammagl/data/download.py
Allow github proxy to download dataset from github.
How to trigger:
export GGL_GITHUB_PROXY=TRUE
=> [Feature] allow github proxy

examples/mixhop/mixhop_trainer.py, examples/mixhop/readme.md, gammagl/layers/conv/__init__.py, gammagl/layers/conv/mixhop_conv.py, gammagl/models/__init__.py, gammagl/models/mixhop.py
The implementation of the model MixHop
=> [Model] add model MixHop

examples/gat/gat_trainer.py, gammagl/models/gat.py
=> update:gat num_layers

examples/sampler/neighbor_sampler.py, examples/sampler/neighbor_sampler_gpu.py, examples/sampler/readme.md
add sampler in examples and add user guide file.
=> add sampler in examples and add user guide file.

tests/datasets/test_modelnet40.py
add a new test file of modelnet40 dataset
=> add test_modelnet40.py

tests/datasets/test_imdb.py
IMDB is a heterogeneous graph containing three types of entities - movies (4,278 nodes), actors (5,257 nodes), and directors (2,081 nodes). The movies are divided into three classes (action, comedy, drama) according to their genre. Movie features correspond to elements of a bag-of-words representation of its plot keywords.
=> test_imdb.py

tests/layers/conv/test_hgt_conv.py
it is a test about hgt.py,we find that it doesn't work while the dimension of inputs are different.
=> [test]test_hgt

tests/datasets/test_coauthor.py
it is a test about dataset-coauthor,we run to confirm the output of this dataset
=> [test]coauthor

tests/datasets/ca_grqc.py
This is a test file for loading data from the CA-GrQc datasets
=> [Test] for the CA-GrQc datasets

README.md, examples/grade/aug.py, examples/grade/grade_trainer.py, examples/grade/readme.md, examples/grade/utils.py, gammagl/models/__init__.py, gammagl/models/grade.py
=> [Model] Implement GRADE

.circleci/requirements.txt, README.md, examples/tadw/readme.md, examples/tadw/tadw_trainer.py, gammagl/models/__init__.py, gammagl/models/tadw.py
=> [Model] Add TADW

gammagl/datasets/__init__.py, gammagl/datasets/aminer.py, tests/datasets/test_aminer.py
=> [Dataset] Add AMiner Dataset

README.md, examples/herec/herec_trainer_aminer.py, examples/herec/readme.md, examples/metapath2vec/metapath2vec_trainer_aminer.py, examples/metapath2vec/readme.md
=> [Update] fix bugs

.circleci/config.yml, .circleci/requirements.txt, gammagl/loader/graph_saint.py, gammagl/loader/neighbor_sampler.py, gammagl/sparse/storage.py, tests/conftest.py, tests/datasets/reddit.py, tests/datasets/test_imdb.py, tests/datasets/test_modelnet40.py, tests/layers/conv/test_agnn_conv.py, tests/loader/test_graph_saint.py, tests/loader/test_neighbor_sampler.py, tests/loader/test_node_neighbor_loader.py, tests/utils/test_loop.py
=> [CI] Fix .circleci

docs/source/api/gammagl.datasets.rst, gammagl/datasets/__init__.py, gammagl/datasets/polblogs.py, gammagl/datasets/wikics.py, tests/datasets/test_polblogs.py, tests/datasets/test_wikics.py
=> [Dataset] Add PolBlogs and WikiCS datasets

examples/graphsage/reddit_sage.py, gammagl/datasets/reddit.py, gammagl/models/graphsage.py
=> [Bug] fix reddit

setup.py
=> [setup.py] Update setup.py

gammagl/layers/conv/rgcn_conv.py, tests/layers/conv/test_han_conv.py, tests/utils/test_loop.py
=> fix mindspore

gammagl/mpops/torch.py, gammagl/mpops/torch_ext/cpu/spmm_max_cpu.cpp, gammagl/mpops/torch_ext/cpu/spmm_max_cpu.h, gammagl/mpops/torch_ext/cpu/spmm_mean_cpu.cpp, gammagl/mpops/torch_ext/cpu/spmm_mean_cpu.h, gammagl/mpops/torch_ext/cpu/spmm_sum_cpu.cpp, gammagl/mpops/torch_ext/cpu/spmm_sum_cpu.h, gammagl/mpops/torch_ext/include/gspmm.h, gammagl/mpops/torch_ext/src/gspmm.cpp, gammagl/mpops/torch_ext/src/operators.cpp
=> [Operator] gspmm (add mean & max)

README.md, examples/graphormer/graphormer_trainer.py, gammagl/data/graph.py, gammagl/datasets/molecule_net.py, gammagl/layers/attention/__init__.py, gammagl/layers/attention/centrality_encoder.py, gammagl/layers/attention/edge_encoder.py, gammagl/layers/attention/graphormer_layer.py, gammagl/layers/attention/spatial_encoder.py, gammagl/models/__init__.py, gammagl/models/graphormer.py, gammagl/utils/__init__.py, gammagl/utils/convert.py, gammagl/utils/shortest_path.py, gammagl/utils/smiles.py, ggl_build_extension.py, setup.py
=> [Model] add graphormer

examples/database/cora_dataset.py, examples/database/cora_sage.py, examples/database/readme.md
=> Add graph database example

examples/gnnlfhf/gnnlfhf_trainer.py, examples/gnnlfhf/readme.md, gammagl/data/__init__.py, gammagl/data/download.py, gammagl/datasets/__init__.py, gammagl/datasets/yelp.py, gammagl/models/__init__.py, gammagl/models/gnnlfhf.py, tests/datasets/test_yelp.py
=> [Model] add gnnlfhf

examples/dfad_gnn/readme.md, examples/dfad_gnn/train_student.py, examples/dfad_gnn/train_teacher.py, gammagl/models/__init__.py, gammagl/models/dfad.py
=> [Model] add dfad-gnn

gammagl/layers/conv/gat_conv.py, gammagl/layers/conv/gcn_conv.py, gammagl/layers/conv/message_passing.py, gammagl/mpops/torch_ext/cpu/bspmm_sum_cpu.cpp
=> update message passing

examples/database/graph_store/prepare_data.py, examples/database/graph_store/reddit_sage_trainer.py, gammagl/data/__init__.py, gammagl/data/feature_store.py, gammagl/data/graph_store.py, gammagl/utils/mixin.py
=> [Data] add graph_store & feature_store

gammagl/mpops/torch_ext/cpu/bspmm_sum_cpu.cpp, gammagl/ops/segment/cpu/segment_csr.cpp, profiler/mpops/complete_test/mp_cpu/bspmm_sum_cpu.py, setup.py
=> [setup.py] update extension module

gammagl/mpops/__init__.py, gammagl/mpops/jittor.py
=> [Ops] Add jittor mpops

examples/llmrec/LLM_augmentation_construct_prompt/gpt_i_attribute_generate_aug.py, examples/llmrec/LLM_augmentation_construct_prompt/gpt_ui_aug.py, examples/llmrec/LLM_augmentation_construct_prompt/gpt_user_profiling.py, examples/llmrec/Models.py, examples/llmrec/llmrec.py, examples/llmrec/readme.md, examples/llmrec/utility/batch_test.py, examples/llmrec/utility/load_data.py, examples/llmrec/utility/logging.py, examples/llmrec/utility/metrics.py, examples/llmrec/utility/norm.py, examples/llmrec/utility/parser.py, examples/nlgraph/README.md, examples/nlgraph/evaluation/connectivity.py, examples/nlgraph/evaluation/cycle.py, examples/nlgraph/evaluation/flow.py, examples/nlgraph/evaluation/gnn.py, examples/nlgraph/evaluation/hamilton.py, examples/nlgraph/evaluation/matching.py, examples/nlgraph/evaluation/shortest_path.py, examples/nlgraph/evaluation/topology.py, examples/nlgraph/generation/shortest_path.py, examples/walklm/WalkLM/README.md, examples/walklm/WalkLM/emb.py, examples/walklm/WalkLM/lp.py, examples/walklm/WalkLM/nc.py
- LLMRec: Large Language Models with Graph Augmentation for Recommendation
- Can language models solve graph problems in natural language?
- WalkLM: a uniform language model fine-tuning framework for attributed graph embedding
add 3 files into example folder
=> [Examples]Add 3 graph foundation model examples:LLMRec/NLGraph/WalkLM
